### ISSUE TITLE
Error in search of film

### ISSUE THREAD

**Issue by Thecave3** [nicholas0g/rivertorrent#1]
La ricerca sul sito non funziona
L'errore può essere riprodotto cercando dai film un titolo qualsiasi

![image](https://user-images.githubusercontent.com/14928080/30720146-94422dac-9f26-11e7-9d70-40603b2a9715.png)

**Comment by nicholas0g** [comment]
Sistemato su Git, entro qualche giorno sarà fatta la pull sui server
